# Generated by Django 2.2.5 on 2020-11-19 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='info',
            field=models.TextField(default='I am a staff member', help_text='Personal Info', max_length=1000),
        ),
    ]
