# Generated by Django 2.2.5 on 2020-11-24 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='importance',
            field=models.CharField(help_text='Level of importance ', max_length=20),
        ),
    ]
